spring:
   thymeleaf:
       cache: false
       prefix:
          classpath: /templates/
       check-template-location: true
       suffix: .html
       encoding: UTF-8
       mode: HTML5
server:
  port: 8083
keycloak:
  realm: sinosun
  auth-server-url: http://127.0.0.1:8080/auth
  resource: springboot-demo
  ssl-required: external
  credentials:
    secret: 7abc8d61-c47e-43bd-9e36-209ad725bcc3
#  bearer-only: true
#  use-resource-role-mappings: false
  cors: true
#  public-client: true
  security-constraints:
    - authRoles:
        - ROLE_CUSTOMER
      securityCollections:
        - name: customer
          patterns:
            - /customer/*
    - authRoles:
        - ROLE_ADMIN
      securityCollections:
        - name: admin
          patterns:
            - /admin/*

